## Fields
##############
# id integer NOT NULL DEFAULT nextval('wevo_devices_id_seq'::regclass),
# wevo_user_id integer NOT NULL,
# device_type character varying,
# device_token character varying,
# acc_uname character varying,
# acc_secret character varying,
# acc_auth character varying,
# acc_transport character varying,
# acc_proxy character varying,
# acc_proxy_enable character varying DEFAULT '0'::character varying,
# acc_reg_expire character varying,
# acc_prefix character varying,
# acc_avpf_enable character varying DEFAULT '0'::character varying,
# acc_avpf_interval character varying,
# acc_plus_00 character varying,
# acc_disableac character varying,
# audio_eco_can_enable character varying,
# audio_adp_rate_enable character varying,
# audio_codec_rate_lim character varying,
# audio_codec character varying,
# video_enable character varying,
# video_always_initiate character varying,
# video_always_accept character varying,
# video_preset character varying,
# video_size character varying,
# video_overlay character varying,
# video_codec character varying,
# call_use_internal_ringtone character varying,
# call_media_encryption character varying,
# call_dtmf_sipinfo_enable character varying,
# call_dtmf_rfc2833_enable character varying,
# call_auto_answer_enable character varying,
# call_vm_uri character varying,
# chat_encrypt_enable character varying,
# chat_share_server character varying,
# net_wifi_only character varying,
# net_dmode_enable character varying,
# net_stun_turn_server character varying,
# net_ice_enable character varying,
# net_turn_enable character varying,
# net_stun_turn_uname character varying,
# net_stun_turn_pass character varying,
# net_rnd_ports_enable character varying,
# net_sip_port character varying,
# net_push_notify_enable character varying,
# net_ipv6_allow character varying,
# adv_flist_subs_enable character varying,
# adv_bg_enable character varying,
# adv_svc_notify_enable character varying,
# adv_boot_start character varying,
# adv_pa_dname character varying,
# adv_pa_uname character varying,
# device_token2 character varying,
# created_at timestamp without time zone NOT NULL,
# updated_at timestamp without time zone NOT NULL
##############

class WevoDevice < ApplicationRecord
  belongs_to :wevo_user
end
